swagger: '2.0'
info:
  title: Image Mood Classifier Example
  version: "0.2"
consumes:
  - application/json
produces:
  - application/json
paths:
  /transform:
    post:
      operationId: app.transform
      summary: Post CSV/JSON data for mood determination
      parameters:
        - $ref: '#/parameters/class_predictions'
        - $ref: '#/parameters/rich_output'
      responses:
        200:
          description: Image mood processed

parameters:
  class_predictions:
    name: class_predictions
    description: Predicted class data
    in: formData
    type: file
    required: true
  rich_output:
    name: rich_output
    description: Rich or regular output
    in: formData
    type: boolean
    required: false
    default: true
